name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # If you need a database or other services, define them here
      # my-service:
      #   image: my-service-image
      #   ports:
      #     - 8080:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run tests
        run: |
          pytest tests  # Specify the path to your tests
