name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      my-service:
        image: my-service-image
        ports:
          - 8080:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-playwright-test .

      - name: Run tests
        run: docker run --rm my-playwright-test
